services:
- type: web
  name: flask-postgres-api
  runtime: python
  repo: https://github.com/firepenguindisopanda/INFO3604-help-desk-rostering
  plan: free
  branch: main
  healthCheckPath: /healthcheck
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn wsgi:app"
  envVars:
  - fromGroup: flask-postgres-api-settings
  - key: DATABASE_URL
    fromDatabase:
      name: flask-postgres-api-db
      property: connectionString 

envVarGroups:
- name: flask-postgres-api-settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py
    

databases:
- name: helpdesk-roster
  plan: free
  databaseName: flask_postgres_api_db