from .admin import *
from .allocation import *
from .auth import *
from .availability import *
from .course import *
from .dashboard import *
from .help_desk_assistant import *
from .initialize import *
from .lab_assistant import *
from .notification import *
from .password_reset import *
from .registration import *
from .request import *
from .schedule import *
from .semester import *
from .shift import *
from .student import *
from .tracking import *
from .user import *
