from .admin import *
from .allocation import *
from .availability import *
from .course_capability import *
from .course import *
from .help_desk_assistant import *
from .notification import *
from .password_reset import *
from .registration_request import *
from .request import *
from .schedule import *
from .semester import *
from .shift_course_demand import *
from .shift import *
from .student import *
from .time_entry import *
from .user import *
