from .admin import *
from .allocation import *
from .availability import *
from .course import *
from .course_capability import *
from .help_desk_assistant import *
from .notification import *
from .schedule import *
from .semester import *
from .shift import *
from .shift_course_demand import *
from .student import *
from .user import *